[package]
name = "topo_digraph_xml"
version = "0.9.4"
authors = ["Rob Johnston <rob.johnston@joyent.com>"]
license = "MIT"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_derive = "*"
serde-xml-rs = "0.3.1"
